### ISSUE TITLE
Should we change <div> to <img />

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#15]
Hi! I'd like to discuss whether we should change the <div> with background approach by a <img/> tag.
What are the pros and cons?

**Comment by eduardomrodrigues** [comment]
In my opinion, this tags must change, why? Let me explain:
My major argument is the semantic of HTML's tag. In Card react component, the image is really significant, mean something very important, it's a part of content, so this is a <img>. The <div> with background means to HTML a beautiful div and this is not what the Card image means. **When we lost the semantic of HTML, we lost the accessibility too.**

But we have some issue with this change: 
Transitions in CSS, when we use the background-image are very simple and powerfull. 
The sprite technique is very performatic

My conclusion: 
We can't pay the price of lose the semantics in HTML for so tiny advantages

I really want to hear you!


PS:
Sorry for my bad english! I'm still pratice

**Comment by JapneetSingh5** [comment]
I agree with @eduardomrodrigues. For the transition part we can harvest some react library, I'm sure we will find one which solves our particular problem.

**Comment by bearcub3** [comment]
@eduardomrodrigues 
First of all, thank you for your opinion. I was wondering if you know the benefit of the Semantic markup. 
It's not only for the accessibility but also for SEO optimization as well. As you mentioned about the accessibility, I am not sure if you have checked my codes. I already have added the role and aria-label attibutes for the divs in order to make the them more accessible and meaningful. I don't think there is a difference between using <img /> and <div /> with role, aria-label attributes programmatically. 

Furthermore, I prefer the <div /> with WAI-ARIA since we can make it more scalable easily as we grow our project. with <img /> element, we can only use image files such as gif, png, to name a few, but with <div /> element, we can add any types of images including SVG, Icons or just any other elements which are not even images. As the cards will be mainly visual presentational purpose, unfortunately visually impaired people would have the restricted experience and all we can do is at least to give the small indication what element it is and what it is for.

**Comment by bearcub3** [comment]
I don't think you are wrong. There are so many ways to add images into the DOM. and sometimes the simplest and straight-forward solution is the best one.

**Comment by eduardomrodrigues** [comment]
@bearcub3, first of all! Very rich comment! 
When I saw this discussion I believed the <img> tag was undoubtedly the best. But your comment show me I was wrong.
You have very good points!
I'll try to make my argument stronger: 
With semantics in mind, the <img /> and the <div /> with background image have significant difference.
For instance, when I ask to myself what are the Card Component children, I answer: image and not a division with background image.
(I don't know if I make myself clear now, sorry)

I understand you don't want to destroy all html's semantics. It's specifically for this case.
But, even for this case I vote to respect the power of img tag semantics and suffer the consequences.

Your code are very concern with accessibility, you are right. Sorry, if I said that in other way

Thank's again, there are very productive discussion!

Thanks, @JapneetSingh5!

**Comment by tiagostutz** [comment]
Background image have save me thousands of time when <img/> just behaviored odd in different browsers. But I think this era is over and the browsers are behaving pretty much the same now.

As we can achieve the same levels of accessibility and SEO on both approaches, I think we should go with `<img />` because at the most basic level of HTML/CSS, `background-image` is intented for styling the content and the `<img />` is intented for composing the content.
As the image here is more a content than a style thing, I vote for using `<img />` tag.

So, let's go this way?

**Comment by bearcub3** [comment]
ok, I am cool with the unanimous decision. Everyone think `<img />` is more appropriate.  That's the way we should go then. I thought images were mainly for styling. 😄

**Comment by tiagostutz** [comment]
All right.!

@giteshk11 would you like to take this one to try out with styled-components? 🤓 

The task is relatively simple, to change the image the card image from `<div>` to `<img>`.

**Comment by giteshk11** [comment]
@tiagostutz Sure, I'll start working on it.
