### ISSUE TITLE
Theming vs Styled Components. Any thoughts?

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-embed#23]
I was thinking about creating a theming structure for this, but I was wondering how to do so with styled components. I mean, I'd like to make it possible for a CSS person that knows how to build a Bootstrap theme, Material Design theme to build a  SA (Stop Analyzing) theme just knowing the CSS rules that must be built, in the same way with those UI Frameworks.
But, with styled components it seems to me that this theming feature won't be that easy to be built. 

I don't have enougth experience with that so I'm not comfortable to make assumptions of decisions without listening from other devs here....

@giteshk11 I was thinking about opening this themeing issue for you, what do you think about the subject and would you like to take this one?

@bearcub3 @jairsjunior @JapneetSingh5 @eduardomrodrigues   If you could give your opinion on that, it would be nice. 😃

**Comment by giteshk11** [comment]
Sure I can work it.
I think we can use mix and match both approaches maybe and I don't have much idea about styled-components.

**Comment by bearcub3** [comment]
styled-components has the same concept like react UI components, breaking it down and make them reusable as components, they are just styled elements composed like react components. When it comes to theming, my understanding so far wouldn't be the same as other bootstraps as I mentioned before since we actually build pre-stylied components, we don't create the styles based on classes. The other good thing about using styled-components, it covers the cross-browsing in the most of cases.  We can create global variables and export them as module in the styled-components. I hope this helps.

**Comment by tiagostutz** [comment]
@bearcub3 thank you for your explanation.!!

I know that I've agreed with styled components, but as this will limit the possibilities of contribution because new contributors that are HTML/CSS devs and don't know React and styled components won't be able to contribute in theming and I think this would be a signficant drawback. 

So, I'm proposing for us to go to a more CSS native approach, more like Bootstrap and other CSS Frameworks instead of styled components. 

That's a proposal, not a decision. What do you think?

**Comment by tiagostutz** [comment]
Hi everyone. As we started a more focused discussion towards implementation in #30 I'm closing this issue. But if someone wants to reopen this discussion, please reopen the issue and feel free to bring back the discussion.

Thanks for all the contributions. It's been a honor.
